### ISSUE TITLE
Default port conflict with Logitech Updater

### ISSUE THREAD

**Issue by scj643** [bootleg/ret-sync#61]
The Logitech updater application listens on the same port that ret-sync does on Windows.

![image](https://user-images.githubusercontent.com/5656510/105891778-0586d400-5fdf-11eb-856c-026521da70e3.png)

We should consider changing the default port.

**Comment by bootleg** [comment]
Hi @scj643 

well indeed, a couple of issues have been open due to this conflict recently. To be fair that port was picked for the plugin almost 10 years ago, they should cease and desist first :)

More practically this can be avoided with a `.sync` conf file like:

```
[INTERFACE]
host=127.0.0.1
port=9234
```

And I'll add a note about that incompatibility in the README as well.

**Comment by bootleg** [comment]
Please see commit: 
https://github.com/bootleg/ret-sync/commit/fbd15e23c4f628ac1eb36ba758a26379eb585d6b
