### ISSUE TITLE
ida 7.2 not found ret-sync plugin 

### ISSUE THREAD

**Issue by adrian-rt** [bootleg/ret-sync#77]
similar issue to : https://github.com/bootleg/ret-sync/issues/50 

I have the same problem with IDA 7.2
I don't see any log file being created even though I've enabled logging as above.

Plugin is copied in C:\Users\adria\AppData\Roaming\Hex-Rays\IDA Pro\Plugins

Do I need to have an ext_ida folder in plugins and inside it retsync folder and SyncPlugin.py? Or I need to have retsync + SyncPlugin.py directly in the plugins folder? anyway I tried both options and nothing seems to work.

Thanks.

**Comment by bootleg** [comment]
Hi @adrian-rt 

Copying `retsync`  folder and ` SyncPlugin.py` (ie. the content of `ext_ida` folder) directly in the plugins folder is enough.

So far retsync does not appear in the quick plugin view (ctrl+3) right?

Is your Python setup properly configured in IDA (is it possible to run a Python script through Script File (Alt+F7) ?

**Comment by adrian-rt** [comment]
problem sorted, I reinstalled python and it works now, thanks.

**Comment by Wuming-sir** [comment]
To add to this, 

"Is your Python setup properly configured in IDA (is it possible to run a Python script through Script File (Alt+F7) ?"

My Python is not properly configured. Instead of reinstalling, what I did was to do go to HKEY_CURRENT_USER\Software\Hex-Rays\IDA, and add Python3TargetDLL = <path to python3.dll>

Hope this helps someone.

**Comment by Zuretek** [comment]
I encountered the same problem with Re-Sync not being detected by IDA 7.7 and the terminal showed me python errors when starting the program like: (C:\Program FilesIDA 7.7\plugins\SyncPlugin.py ...)
the problem in my case was caused by python 3.9, I uninstalled it and instead installed version 3.8.8 and it worked, I hope this helps.
