### ISSUE TITLE
ida 7.7 compatibility

### ISSUE THREAD

**Issue by johdcmlaker2000** [bootleg/ret-sync#85]
IDA plugin is crashing during run in the 7.7 version of the IDA. No crash after SyncPlugin.py file deleting.

```
Further work is not possible and IDA will close.
Would you like to create a crash dump for a bug report?

IDA has encountered a problem.
It is recommended to save your work and restart IDA.
A mini dump file has been created in 'ida-20220111-194417-24272.dmp'
Please send it to <support@hex-rays.com>```

**Comment by bootleg** [comment]
Hi @johdcmlaker2000 

Would it be possible for you to share the output of the Windbg command "`!analyze -v`" for the minidump ? Is it a 32 or 64-bit IDA ?

I have been unable to reproduce the crash locally with IDA 7.7. 

Best regards, 
bootleg.

**Comment by johdcmlaker2000** [comment]
i get such error for both IDA x86 and x64:

  File "C:/IDA Pro 7.7/plugins/SyncPlugin.py", line 42, in <module>
    from PyQt5 import QtCore, QtWidgets
AttributeError: 'module' object has no attribute 'IntEnum'

when i open any binary or idb i get crash. Python is 2.7 x64.

**Comment by bootleg** [comment]
Hello @johdcmlaker2000 

with the elements above I have been able to reproduce the error above (not a crash though). The issue is only present for Python 2.7. The versions of the lib packaged with the latest IDA 7.7 release seems not to be compatible anymore with it . As Python 2.7 is mostly EOL, I'd recommend switching to a more future-proof Python 3 setup (at least for IDA here).

Is that ok for you to close the issue?

**Comment by johdcmlaker2000** [comment]
bootleg, thank you for your help, i'm closing the issue
